# Generated by Django 5.0 on 2024-02-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_textdetails_textdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdetail',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='textdetail',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
