# Generated by Django 5.0 on 2023-12-09 11:41

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('e_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=252)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('pan_no', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=core.models.user_image_upload_path)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to=core.models.user_aadhar_upload_path)),
                ('pan_file', models.FileField(blank=True, null=True, upload_to=core.models.user_pan_upload_path)),
                ('blood_group', models.CharField(max_length=5)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_code', models.CharField(editable=False, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_package', models.IntegerField(blank=True, null=True)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
