# Generated by Django 5.0 on 2023-12-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
